#!/usr/bin/env python3
"""Draw the house-style SVG thumbnails in thumbs/.

One file per entry, named after the repo: thumbs/<name>.svg, 150 x 150, no text.

House style
  * one background, BG, everywhere;
  * line art in white plus a six-step ramp of reds, thin strokes, no fills to speak of;
  * a 16 px inner margin, so the CSS can round the corners without cutting anything.

Where it can, a thumbnail redraws something real from the project:
  Projections                        Figure 1 of the essay: the vector (3, 7) and its coordinates
  Naive-Discrete-Fourier-Transform   the toy signal and coefficient magnitudes from naive_dft_ish.py
                                     (recomputed here with the same formula)
  Stryder                            the 100 epoch losses printed in neural-obfuscation.ipynb
Eliza, Ellie and Ada have no data to plot, so they get drawings of what they do.
Any other repo name gets an abstract plot (fan, bundle, contour, scatter or rose) chosen by
hashing the name, so it never changes between builds.

Usage
    python scripts/thumbs.py                 # every entry in content/projects.yaml
    python scripts/thumbs.py --name MyRepo   # one name, even if it is not in the YAML yet
    python scripts/thumbs.py --force         # also overwrite files you drew by hand
    python scripts/thumbs.py --list          # show which style each name gets

Swapping in your own: save your SVG (or PNG) over thumbs/<name>.svg. Generated files start
with a marker comment; a file without it is treated as yours and left alone unless --force.
"""
from __future__ import annotations

import argparse
import hashlib
import math
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
THUMBS = ROOT / "thumbs"
CONTENT = ROOT / "content" / "projects.yaml"
MARK = "generated by scripts/thumbs.py"

# ---- house style --------------------------------------------------------------------------
BG = "#333333"
WHITE = "#ffffff"
REDS = ["#ffd4cc", "#ff9f90", "#ff6a55", "#e5392a", "#b3231a", "#8a1f18"]   # light -> dark
SIZE = 150
M = 16          # inner margin
THIN, BASE, BOLD = 0.75, 1.0, 1.6


# ---- tiny helpers -------------------------------------------------------------------------
def n(x: float) -> str:
    """Short number: at most one decimal, no trailing zeros."""
    s = f"{x:.1f}"
    s = s.rstrip("0").rstrip(".") if "." in s else s
    return "0" if s in ("-0", "") else s


def w(x: float) -> str:
    """Width or opacity: at most two decimals, no trailing zeros."""
    s = f"{x:.2f}".rstrip("0").rstrip(".")
    return s or "0"


def seed_of(name: str) -> int:
    return int.from_bytes(hashlib.sha256(name.encode("utf-8")).digest()[:8], "big")


class Rng:
    """SplitMix64. Own generator so the output never depends on the Python version."""
    MASK = (1 << 64) - 1

    def __init__(self, seed: int):
        self.s = seed & self.MASK

    def _next(self) -> int:
        self.s = (self.s + 0x9E3779B97F4A7C15) & self.MASK
        z = self.s
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & self.MASK
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & self.MASK
        return z ^ (z >> 31)

    def random(self) -> float:
        return (self._next() >> 11) / float(1 << 53)

    def uniform(self, a: float, b: float) -> float:
        return a + (b - a) * self.random()

    def normal(self, mu: float = 0.0, sigma: float = 1.0) -> float:
        u1 = max(self.random(), 1e-12)
        return mu + sigma * math.sqrt(-2.0 * math.log(u1)) * math.cos(2 * math.pi * self.random())

    def int(self, a: int, b: int) -> int:
        return a + self._next() % (b - a + 1)

    def choice(self, seq):
        return seq[self._next() % len(seq)]


class Canvas:
    def __init__(self) -> None:
        self.parts: list[str] = []

    def add(self, s: str) -> None:
        self.parts.append(s)

    def path(self, pts, color=WHITE, width=BASE, opacity=1.0, dash=None, close=False, fill="none") -> None:
        if len(pts) < 2:
            return
        d = "M" + " ".join(f"{n(x)} {n(y)}" for x, y in pts) + ("Z" if close else "")
        self.add(f'<path d="{d}"{self._style(color, width, opacity, dash, fill)}/>')

    def line(self, x1, y1, x2, y2, color=WHITE, width=BASE, opacity=1.0, dash=None) -> None:
        self.path([(x1, y1), (x2, y2)], color, width, opacity, dash)

    def circle(self, cx, cy, r, color=WHITE, width=BASE, opacity=1.0, filled=False) -> None:
        if filled:
            self.add(f'<circle cx="{n(cx)}" cy="{n(cy)}" r="{n(r)}" fill="{color}"{self._op(opacity)} stroke="none"/>')
        else:
            self.add(f'<circle cx="{n(cx)}" cy="{n(cy)}" r="{n(r)}"{self._style(color, width, opacity, None, "none")}/>')

    def rect(self, x, y, w, h, color=WHITE, width=BASE, opacity=1.0, rx=0.0) -> None:
        r = f' rx="{n(rx)}"' if rx else ""
        self.add(f'<rect x="{n(x)}" y="{n(y)}" width="{n(w)}" height="{n(h)}"{r}{self._style(color, width, opacity, None, "none")}/>')

    @staticmethod
    def _op(opacity: float) -> str:
        return "" if opacity >= 1 else f' fill-opacity="{w(opacity)}"'

    @staticmethod
    def _style(color, width, opacity, dash, fill) -> str:
        s = f' fill="{fill}" stroke="{color}" stroke-width="{w(width)}"'
        if opacity < 1:
            s += f' stroke-opacity="{w(opacity)}"'
        if dash:
            s += f' stroke-dasharray="{dash}"'
        return s

    def svg(self, note: str = "") -> str:
        body = "\n".join(self.parts)
        return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}" width="{SIZE}" height="{SIZE}">\n'
                f'<!-- {MARK}{(" | " + note) if note else ""} -->\n'
                f'<rect width="{SIZE}" height="{SIZE}" fill="{BG}"/>\n'
                f'<g stroke-linecap="round" stroke-linejoin="round">\n{body}\n</g>\n</svg>\n')


def ramp(i: int, count: int, reverse: bool = False) -> str:
    """Pick a red from the ramp for position i of count (0 = lightest unless reverse)."""
    t = i / max(count - 1, 1)
    if reverse:
        t = 1 - t
    return REDS[min(int(round(t * (len(REDS) - 1))), len(REDS) - 1)]


def arrow_head(c: Canvas, x, y, ang, size=6.0, color=WHITE, width=BASE, spread=0.45) -> None:
    for s in (-1, 1):
        a = ang + math.pi + s * spread
        c.line(x, y, x + size * math.cos(a), y + size * math.sin(a), color, width)


def frame_grid(c: Canvas, x0, y0, x1, y1, nx, ny, opacity=0.10) -> None:
    for i in range(nx + 1):
        x = x0 + (x1 - x0) * i / nx
        c.line(x, y0, x, y1, WHITE, THIN, opacity)
    for j in range(ny + 1):
        y = y0 + (y1 - y0) * j / ny
        c.line(x0, y, x1, y, WHITE, THIN, opacity)


# ---- marching squares ---------------------------------------------------------------------
_CASES = {1: [("L", "B")], 2: [("B", "R")], 3: [("L", "R")], 4: [("T", "R")], 5: [("T", "L"), ("B", "R")],
          6: [("T", "B")], 7: [("T", "L")], 8: [("T", "L")], 9: [("T", "B")], 10: [("T", "R"), ("L", "B")],
          11: [("T", "R")], 12: [("L", "R")], 13: [("B", "R")], 14: [("L", "B")]}


def contour_segments(f, x0, y0, x1, y1, nx, ny, level):
    xs = [x0 + (x1 - x0) * i / nx for i in range(nx + 1)]
    ys = [y0 + (y1 - y0) * j / ny for j in range(ny + 1)]
    v = [[f(x, y) for x in xs] for y in ys]
    segs = []

    def cross(p, q, a, b):
        t = (level - a) / (b - a) if b != a else 0.5
        return (p[0] + t * (q[0] - p[0]), p[1] + t * (q[1] - p[1]))

    for j in range(ny):
        for i in range(nx):
            tl, tr, br, bl = (xs[i], ys[j]), (xs[i + 1], ys[j]), (xs[i + 1], ys[j + 1]), (xs[i], ys[j + 1])
            vtl, vtr, vbr, vbl = v[j][i], v[j][i + 1], v[j + 1][i + 1], v[j + 1][i]
            idx = (vtl > level) * 8 + (vtr > level) * 4 + (vbr > level) * 2 + (vbl > level) * 1
            if idx in (0, 15):
                continue
            e = {"T": cross(tl, tr, vtl, vtr), "R": cross(tr, br, vtr, vbr),
                 "B": cross(bl, br, vbl, vbr), "L": cross(tl, bl, vtl, vbl)}
            for a, b in _CASES[idx]:
                segs.append((e[a], e[b]))
    return segs


def chain(segs):
    key = lambda p: (round(p[0], 2), round(p[1], 2))
    ends: dict = {}
    for i, (a, b) in enumerate(segs):
        ends.setdefault(key(a), []).append(i)
        ends.setdefault(key(b), []).append(i)
    used = [False] * len(segs)
    out = []
    for i in range(len(segs)):
        if used[i]:
            continue
        used[i] = True
        line = [segs[i][0], segs[i][1]]
        for head in (False, True):
            while True:
                tip = key(line[0] if head else line[-1])
                nxt = next((j for j in ends.get(tip, []) if not used[j]), None)
                if nxt is None:
                    break
                used[nxt] = True
                p, q = segs[nxt]
                other = q if key(p) == tip else p
                line.insert(0, other) if head else line.append(other)
        out.append(line)
    return out


# ---- real-data thumbnails -----------------------------------------------------------------
def g_projections(name: str) -> str:
    """Figure 1 of the essay: v = (3, 7) and its projections on the axes."""
    c = Canvas()
    ox, oy, u = 24.0, 126.0, 10.6          # origin and pixels per unit; axes run 0..10
    for k in range(0, 11, 2):
        c.line(ox + k * u, oy, ox + k * u, oy - 10 * u, WHITE, THIN, 0.12)
        c.line(ox, oy - k * u, ox + 10 * u, oy - k * u, WHITE, THIN, 0.12)
    c.line(ox, oy, ox + 10.6 * u, oy, WHITE, BASE, 0.9)
    c.line(ox, oy, ox, oy - 10.6 * u, WHITE, BASE, 0.9)
    arrow_head(c, ox + 10.6 * u, oy, 0.0, 5, WHITE, BASE)
    arrow_head(c, ox, oy - 10.6 * u, -math.pi / 2, 5, WHITE, BASE)
    vx, vy = ox + 3 * u, oy - 7 * u
    c.line(vx, oy, vx, vy, WHITE, THIN, 0.55, "2.5 2.5")           # guide to the x axis
    c.line(ox, vy, vx, vy, WHITE, THIN, 0.55, "2.5 2.5")           # guide to the y axis
    c.line(ox, oy, vx, oy, REDS[3], BOLD)                           # coordinate on x
    c.line(ox, oy, ox, vy, REDS[3], BOLD)                           # coordinate on y
    c.line(vx, oy - 3, vx, oy + 3, WHITE, BASE)                     # ticks at 3 and 7
    c.line(ox - 3, vy, ox + 3, vy, WHITE, BASE)
    ang = math.atan2(vy - oy, vx - ox)
    c.line(ox, oy, vx - 3 * math.cos(ang), vy - 3 * math.sin(ang), REDS[1], BOLD)
    arrow_head(c, vx, vy, ang, 6.5, REDS[1], BOLD)
    c.circle(ox, oy, 1.8, WHITE, filled=True)
    return c.svg("Figure 1 of Projections: v = (3, 7)")


def _ndft_data():
    """Same signal and probe as naive_dft_ish.py: 10,000 samples on [0, 1], n = 1..10."""
    N = 10000
    t = [i / (N - 1) for i in range(N)]
    two_pi = 2 * math.pi

    def f(x):
        return (3 * math.cos(two_pi * x) + 12 * math.cos(two_pi * 2 * x) - 0.8 * math.sin(two_pi * 3 * x)
                + 15 * math.cos(two_pi * x * 5) + 100 * math.sin(two_pi * 7 * x))

    vals = [f(x) for x in t]
    mags = []
    for k in range(1, 11):
        re = im = 0.0
        prev = None
        for x, fx in zip(t, vals):
            a, b = fx * math.cos(two_pi * k * x), -fx * math.sin(two_pi * k * x)     # f * exp(-2 pi i k t)
            if prev is not None:
                dx = x - prev[0]
                re += 0.5 * (a + prev[1]) * dx
                im += 0.5 * (b + prev[2]) * dx
            prev = (x, a, b)
        mags.append(2 * math.hypot(re, im))
    return f, mags


def g_ndft(name: str) -> str:
    f, mags = _ndft_data()
    c = Canvas()
    x0, x1 = M, SIZE - M
    top_mid, amp = 46.0, 27.0
    c.line(x0, top_mid, x1, top_mid, WHITE, THIN, 0.18)
    pts = [(x0 + (x1 - x0) * i / 239, top_mid - amp * f(i / 239) / 131.0) for i in range(240)]
    c.path(pts, WHITE, BASE, 0.95)
    base, tall = 128.0, 50.0
    c.line(x0, base, x1, base, WHITE, THIN, 0.45)
    peak = max(mags)
    for k, m in enumerate(mags, start=1):
        x = x0 + (x1 - x0) * (k - 0.5) / 10
        h = tall * m / peak
        col = WHITE if m == peak else ramp(k, 11)
        if h > 0.4:
            c.line(x, base, x, base - h, col, BASE)
        c.circle(x, base - h, 1.9 if m == peak else 1.5, col, filled=m == peak)
    return c.svg("signal and magnitudes recomputed from naive_dft_ish.py")


# epoch losses printed in Stryder's neural-obfuscation.ipynb (epochs 1..100)
STRYDER_LOSS = [1.7642, 0.6842, 0.4055, 0.2972, 0.2398, 0.2043, 0.1781, 0.1579, 0.1393, 0.1228, 0.1079, 0.0953,
                0.0837, 0.0735, 0.0649, 0.0573, 0.0508, 0.0455, 0.0411, 0.0376, 0.0347, 0.0317, 0.0299, 0.0278,
                0.0263, 0.0245, 0.0233, 0.0217, 0.0204, 0.0197, 0.0186, 0.0175, 0.0169, 0.0163, 0.0154, 0.0148,
                0.0145, 0.0137, 0.0133, 0.0127, 0.0123, 0.0119, 0.0114, 0.0111, 0.0107, 0.0108, 0.0099, 0.0096,
                0.0097, 0.0092, 0.009, 0.0087, 0.0086, 0.0083, 0.0079, 0.008, 0.0076, 0.0074, 0.0075, 0.007,
                0.0069, 0.0069, 0.007, 0.0063, 0.0063, 0.0063, 0.0061, 0.0061, 0.0057, 0.0056, 0.0058, 0.0055,
                0.0054, 0.0054, 0.0052, 0.0051, 0.0055, 0.0045, 0.0048, 0.0049, 0.0047, 0.0045, 0.0049, 0.0042,
                0.0046, 0.0045, 0.0043, 0.0042, 0.0043, 0.0039, 0.0041, 0.0039, 0.004, 0.0039, 0.0038, 0.0037,
                0.0038, 0.0036, 0.0036, 0.0039]


def g_stryder(name: str) -> str:
    c = Canvas()
    x0, x1, y0, y1 = M + 2, SIZE - M, M + 2, SIZE - M - 4        # plot box
    lo, hi = math.log10(0.003), math.log10(2.5)

    def X(e):
        return x0 + (x1 - x0) * (e - 1) / 99

    def Y(v):
        return y1 - (y1 - y0) * (math.log10(v) - lo) / (hi - lo)

    for decade in (1.0, 0.1, 0.01):                              # decade lines on the log axis
        c.line(x0, Y(decade), x1, Y(decade), WHITE, THIN, 0.14)
    c.line(x0, y0, x0, y1, WHITE, THIN, 0.5)
    c.line(x0, y1, x1, y1, WHITE, THIN, 0.5)
    for e in range(1, 101, 2):                                   # shading under the curve
        v = STRYDER_LOSS[e - 1]
        c.line(X(e), Y(v), X(e), y1, ramp(e, 100, reverse=True), THIN, 0.8)
    c.path([(X(e), Y(v)) for e, v in enumerate(STRYDER_LOSS, start=1)], WHITE, BASE + 0.25)
    c.circle(X(100), Y(STRYDER_LOSS[-1]), 2.0, WHITE, filled=True)
    return c.svg("epoch losses from neural-obfuscation.ipynb, log scale")


# ---- drawings of what a project does --------------------------------------------------------
def g_eliza(name: str) -> str:
    """The figure Eliza.capm(plot=True) draws: returns scatter, dashed zero lines, fitted line."""
    r = Rng(seed_of(name))
    c = Canvas()
    cx, cy, half = SIZE / 2, SIZE / 2 + 2, SIZE / 2 - M
    c.line(cx, cy - half, cx, cy + half, WHITE, THIN, 0.35, "2.5 2.5")
    c.line(cx - half, cy, cx + half, cy, WHITE, THIN, 0.35, "2.5 2.5")
    beta = 1.3
    pts = []
    for _ in range(46):
        x = max(-1.0, min(1.0, r.normal(0, 0.42)))
        y = max(-1.05, min(1.05, beta * x * 0.62 + r.normal(0, 0.2)))
        pts.append((cx + x * half, cy - y * half))
    for k, (px, py) in enumerate(pts):
        if k % 4 == 0:                                            # a few residuals
            fit = cy - beta * 0.62 * (px - cx)
            c.line(px, py, px, fit, REDS[4], THIN, 0.9)
    for px, py in pts:
        c.circle(px, py, 1.5, WHITE, opacity=0.8, filled=True)
    xa, xb = -0.95, 0.95
    c.line(cx + xa * half, cy - beta * 0.62 * xa * half, cx + xb * half, cy - beta * 0.62 * xb * half, REDS[2], BOLD)
    return c.svg("schematic CAPM scatter, seeded from the name")


def g_ellie(name: str) -> str:
    """A contact sheet: one column per weekday, a frame per photo."""
    r = Rng(seed_of(name))
    c = Canvas()
    fw, fh, gx, gy = 17.0, 22.0, 6.0, 6.0
    cols = 5
    x0 = (SIZE - (cols * fw + (cols - 1) * gx)) / 2
    y0 = M + 4
    hi = (r.int(0, cols - 1), r.int(0, 2))
    for col in range(cols):
        rows = r.int(2, 4)
        x = x0 + col * (fw + gx)
        c.line(x, y0 - 7, x + fw, y0 - 7, ramp(col, cols), BASE)                  # the day's folder rule
        for row in range(rows):
            y = y0 + row * (fh + gy)
            col_c = WHITE if (col, row) == hi else ramp(col, cols)
            c.rect(x, y, fw, fh, col_c, BASE, rx=1.5)
            ridge = [(x + 2, y + fh - 5), (x + fw * 0.35, y + fh - 11 - r.random() * 4),
                     (x + fw * 0.6, y + fh - 7), (x + fw - 2, y + fh - 12 - r.random() * 3)]
            c.path(ridge, col_c, THIN, 0.9)
    return c.svg("a frame per photo, a column per day")


def g_ada(name: str) -> str:
    """Many videos in, one at a time out, with a gap that never shrinks."""
    c = Canvas()
    gate_x, mid = 72.0, SIZE / 2
    n_in = 5
    for i in range(n_in):
        y = M + 6 + i * 22.0
        col = ramp(i, n_in, reverse=True)
        c.rect(M, y - 5, 20, 10, col, BASE, rx=1.5)
        c.path([(M + 20, y), (gate_x - 10, mid)], col, THIN, 0.95)
    c.line(gate_x - 10, mid, gate_x + 6, mid, REDS[2], BASE)
    for dy in (-1, 1):                                                            # the gate
        c.line(gate_x, mid + dy * 5, gate_x, mid + dy * 24, WHITE, BASE)
    c.line(gate_x + 6, mid, SIZE - M, mid, REDS[2], BASE)
    xs = [92.0, 112.0, 132.0]
    for x in xs:
        c.rect(x - 4, mid - 4, 8, 8, WHITE, BASE, rx=1)
    for a, b in zip(xs, xs[1:]):                                                  # the minimum gap
        c.path([(a + 5, mid + 12), (a + 5, mid + 16), (b - 5, mid + 16), (b - 5, mid + 12)], WHITE, THIN, 0.55)
    return c.svg("videos queue, a gate spaces them out")


def g_photo(name: str) -> str:
    """Placeholder portrait: head and shoulders as contour lines."""
    c = Canvas()
    hx, hy = SIZE / 2, 56.0
    for i, rad in enumerate((6, 12, 18, 24, 30)):                                  # head
        col = WHITE if i == 2 else ramp(i + 1, 7)
        c.circle(hx, hy, rad, col, BASE if i == 2 else THIN, 1.0 if i == 2 else 0.9)
    for i, rad in enumerate((62, 72, 82)):                                         # shoulders
        arc = [(hx + rad * math.cos(a), 178 + rad * math.sin(a)) for a in [math.pi + k * math.pi / 48 for k in range(49)]]
        c.path(arc, ramp(i + 1, 7), THIN + 0.1, 0.95)
    return c.svg("placeholder portrait")


# ---- abstract plots for any other name ------------------------------------------------------
def a_fan(name: str) -> str:
    r = Rng(seed_of(name))
    c = Canvas()
    px, py = r.uniform(62, 90), r.uniform(70, 96)
    count = r.int(11, 16)
    base_ang = r.uniform(-1.2, -0.4)
    for i in range(count):
        a = base_ang - i * (r.uniform(1.0, 1.5) / count)
        L = 170
        c.line(px, py, px + L * math.cos(a), py + L * math.sin(a), ramp(i, count), THIN + 0.15, 0.9)
    for i in range(3):
        a = base_ang - 0.18 - i * 0.35
        c.line(px, py, px - 170 * math.cos(a) * 0.5, py - 170 * math.sin(a) * 0.5, REDS[4], THIN, 0.8)
    c.line(M - 6, py + 30, SIZE - M + 6, py + 30, WHITE, BASE, 0.9)
    c.line(px, M - 6, px, SIZE - M + 6, WHITE, BASE, 0.9, "2 3")
    c.circle(px, py, 2, WHITE, filled=True)
    return c.svg("fan")


def a_bundle(name: str) -> str:
    r = Rng(seed_of(name))
    c = Canvas()
    (f1, p1), (f2, p2) = (r.uniform(0.8, 1.6), r.uniform(0, 6.28)), (r.uniform(2.0, 3.4), r.uniform(0, 6.28))

    def centre(t: float) -> float:
        return 0.9 * math.sin(f1 * math.pi * t * 2 + p1) * (1 - 0.35 * t) + 0.25 * math.sin(f2 * math.pi * t * 2 + p2)

    cnt = 13
    x0, x1 = M - 4, SIZE - M + 4
    for i in range(cnt):
        spread = (i - cnt / 2) / cnt
        pts = [(x0 + (x1 - x0) * k / 60, SIZE / 2 - 26 * (centre(k / 60) + spread * 1.6 * k / 60)) for k in range(61)]
        c.path(pts, ramp(abs(i - cnt // 2), cnt // 2 + 1, reverse=True), THIN + 0.1, 0.95)
    c.path([(x0 + (x1 - x0) * k / 60, SIZE / 2 - 26 * centre(k / 60)) for k in range(61)], WHITE, BASE + 0.2)
    return c.svg("bundle")


def a_contour(name: str) -> str:
    r = Rng(seed_of(name))
    c = Canvas()
    bumps = [(r.uniform(-0.5, 0.5), r.uniform(-0.5, 0.5), r.uniform(0.25, 0.5), r.uniform(0.25, 0.5), r.uniform(0.7, 1.0)),
             (r.uniform(-0.6, 0.6), r.uniform(-0.6, 0.6), r.uniform(0.2, 0.4), r.uniform(0.2, 0.4), r.uniform(0.4, 0.8))]

    def f(x, y):
        return sum(a * math.exp(-((x - cx) ** 2 / (2 * sx ** 2) + (y - cy) ** 2 / (2 * sy ** 2))) for cx, cy, sx, sy, a in bumps)

    levels = [0.12, 0.22, 0.34, 0.48, 0.64, 0.82]
    span = 1.0
    for li, lv in enumerate(levels):
        for ch in chain(contour_segments(f, -span, -span, span, span, 36, 36, lv)):
            pts = [(SIZE / 2 + x * (SIZE / 2 - M + 6), SIZE / 2 + y * (SIZE / 2 - M + 6)) for x, y in ch]
            c.path(pts, ramp(li, len(levels), reverse=True), THIN + 0.15, 0.95)
    # a few steps of gradient ascent on f, drawn as a dotted white path
    x, y = r.uniform(-0.8, -0.4), r.uniform(0.4, 0.8)
    pts = [(x, y)]
    for _ in range(9):
        h = 1e-3
        gx, gy = (f(x + h, y) - f(x - h, y)) / (2 * h), (f(x, y + h) - f(x, y - h)) / (2 * h)
        norm = math.hypot(gx, gy) or 1.0
        x, y = x + 0.13 * gx / norm, y + 0.13 * gy / norm
        pts.append((x, y))
    sp = [(SIZE / 2 + px * (SIZE / 2 - M + 6), SIZE / 2 + py * (SIZE / 2 - M + 6)) for px, py in pts]
    c.path(sp, WHITE, BASE, 0.9, "1 2.5")
    for px, py in sp:
        c.circle(px, py, 1.5, WHITE, filled=True)
    return c.svg("contour")


def a_scatter(name: str) -> str:
    r = Rng(seed_of(name))
    c = Canvas()
    m, b = r.uniform(0.4, 0.9), r.uniform(-0.1, 0.1)
    frame_grid(c, M, M, SIZE - M, SIZE - M, 4, 4, 0.10)
    for _ in range(54):
        x = r.uniform(-0.95, 0.95)
        y = max(-0.98, min(0.98, m * x + b + r.normal(0, 0.18)))
        c.circle(SIZE / 2 + x * (SIZE / 2 - M), SIZE / 2 - y * (SIZE / 2 - M), 1.5, WHITE, opacity=0.8, filled=True)
    c.line(SIZE / 2 - 0.95 * (SIZE / 2 - M), SIZE / 2 - (m * -0.95 + b) * (SIZE / 2 - M),
           SIZE / 2 + 0.95 * (SIZE / 2 - M), SIZE / 2 - (m * 0.95 + b) * (SIZE / 2 - M), REDS[2], BOLD)
    return c.svg("scatter")


def a_rose(name: str) -> str:
    r = Rng(seed_of(name))
    c = Canvas()
    k = r.choice([3, 5, 7]) / r.choice([1, 2])
    copies = 6
    for i in range(copies):
        rot = i * math.pi / (k * copies * 1.0)
        pts = []
        for s in range(0, 361, 2):
            th = math.radians(s) * (2 if k != int(k) else 1)
            rad = (0.35 + 0.65 * (i + 1) / copies) * math.cos(k * th)
            pts.append((SIZE / 2 + (SIZE / 2 - M) * rad * math.cos(th + rot), SIZE / 2 + (SIZE / 2 - M) * rad * math.sin(th + rot)))
        c.path(pts, WHITE if i == copies - 1 else ramp(i, copies, reverse=True), THIN + 0.15, 0.95)
    return c.svg("rose")


ABSTRACT = {"fan": a_fan, "bundle": a_bundle, "contour": a_contour, "scatter": a_scatter, "rose": a_rose}
ABSTRACT_ALT = {
    "fan": "A fan of thin red lines spreading from one point, crossed by a white baseline, on dark grey.",
    "bundle": "A bundle of wavy red curves around one white curve, on dark grey.",
    "contour": "Nested red contour lines of a smooth surface with a dotted white path climbing it.",
    "scatter": "A white scatter of points around a red fitted line, on dark grey.",
    "rose": "Overlapping red rose curves with one white curve on top, on dark grey.",
}

# name -> (function, alt text). Names are matched case-insensitively.
BESPOKE = {
    "projections": (g_projections, "Plot of the vector (3, 7) on x and y axes, with dashed guide lines to its coordinates on each axis."),
    "naive-discrete-fourier-transform": (g_ndft, "A summed sine wave above a stem plot of its Fourier coefficient magnitudes, with one tall spike at 7 hertz and four small ones."),
    "stryder": (g_stryder, "Training loss against epoch on a log scale, falling steeply at first and then flattening over 100 epochs."),
    "eliza": (g_eliza, "Scatter of stock returns against market returns with a fitted red line and dashed zero axes."),
    "ellie": (g_ellie, "A grid of photo frames in five columns, one column for each weekday."),
    "ada": (g_ada, "Five rectangles narrowing through a gate into a single line of evenly spaced squares."),
    "photo-placeholder": (g_photo, "Placeholder portrait drawn as concentric contour lines."),
}


def style_of(name: str) -> str:
    key = name.lower()
    if key in BESPOKE:
        return "bespoke"
    return sorted(ABSTRACT)[seed_of(name) % len(ABSTRACT)]


def render(name: str) -> str:
    key = name.lower()
    if key in BESPOKE:
        return BESPOKE[key][0](name)
    return ABSTRACT[style_of(name)](name)


def describe(name: str) -> str:
    """Default alt text for a thumbnail, used by build.py when the YAML has none."""
    key = name.lower()
    if key in BESPOKE:
        return BESPOKE[key][1]
    return ABSTRACT_ALT[style_of(name)]


# ---- favicons -------------------------------------------------------------------------------
def favicon(rounded: bool = True) -> str:
    rx = ' rx="7"' if rounded else ""
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32">\n'
            f'<!-- {MARK} | favicon -->\n'
            f'<rect width="32" height="32"{rx} fill="{BG}"/>\n'
            f'<g fill="none" stroke-linecap="round" stroke-linejoin="round">\n'
            f'<path d="M6 25 L26 8" stroke="{REDS[2]}" stroke-width="2"/>\n'
            f'<path d="M6 9 C12 9 14 24 26 24" stroke="{WHITE}" stroke-width="2"/>\n'
            f'</g>\n</svg>\n')


# ---- cli ------------------------------------------------------------------------------------
def entry_names() -> list[str]:
    try:
        from ruamel.yaml import YAML
    except ImportError:
        sys.exit("ruamel.yaml is needed to read content/projects.yaml (pip install -r requirements.txt), or use --name")
    if not CONTENT.exists():
        return []
    data = YAML().load(CONTENT.read_text(encoding="utf-8")) or {}
    return [str(e.get("id") or (e.get("github") or {}).get("name")) for e in data.get("entries", []) or []
            if not e.get("hidden")]


def write(path: pathlib.Path, text: str, force: bool) -> str:
    if path.exists() and not force and MARK not in path.read_text(encoding="utf-8", errors="ignore")[:400]:
        return "kept (not generated by this script)"
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return "unchanged"
    path.write_text(text, encoding="utf-8")
    return "written"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--name", action="append", help="draw this name (repeatable); default is every entry in the YAML")
    ap.add_argument("--force", action="store_true", help="overwrite files that this script did not generate")
    ap.add_argument("--list", action="store_true", help="show the style chosen for each name and exit")
    args = ap.parse_args()

    names = list(dict.fromkeys((args.name or entry_names()) + ["photo-placeholder"]))
    if args.list:
        for nm in names:
            print(f"{nm:40s} {style_of(nm)}")
        return
    THUMBS.mkdir(exist_ok=True)
    for nm in names:
        print(f"thumbs/{nm}.svg: {write(THUMBS / (nm + '.svg'), render(nm), args.force)}")
    print(f"favicon.svg: {write(ROOT / 'favicon.svg', favicon(True), args.force)}")


if __name__ == "__main__":
    main()
